
import java.util.*;

public class StopWatch extends javax.swing.JFrame implements Runnable{

    Thread t;
    int hcnt = 0, mcnt = 0, scnt =0, mscnt = 0;
    String str ="", nstr ="", mstr ="",dstr="";
    int cnt =0,cnt2=0;

    public StopWatch() {
        initComponents();
        t = new Thread(this);
        reset();
    }
    
    public void reset(){
        hcnt=0; mcnt=0; scnt=0; mscnt=0; cnt2=0;
        nstr="00:00:00"; mstr="000"; dstr="";
        display();
    }
    
    public void display(){
        lblDisp1.setText(nstr);
        lblDisp2.setText(mstr);
    }
    
    public void setTimeCounter(){
        nstr="";
        if(hcnt < 10){
            nstr = "0" + hcnt;
        }
        else{
            nstr = "" + hcnt;
        }
        
        if(mcnt < 10){
            nstr += ":0" + mcnt;
        }
        else{
            nstr += ":" + mcnt;
        }
        
        if(scnt < 10){
            nstr += ":0" + scnt;
        }
        else{
            nstr += ":" + scnt;
        }
    }
    public void setMTimeCounter(){
        mstr="";
        if(mscnt < 10){
            mstr = "00" + mscnt;
        }
        else if(mscnt >=10 && mscnt <100){
            mstr = "0" + mscnt;
        }
        else{
            mstr = "" + mscnt;
        }
    }
    
    public void run(){
        try {
             mscnt++;
                if(mscnt>999){
                    mscnt=0;
                    scnt++;
                }
                 if(scnt>59){
                    scnt=0; 
                    mcnt++;
                }
                 if(mcnt>59){
                    mcnt=0;   
                    hcnt++;
                }
                if(hcnt<99){
                    reset();
                }
                setTimeCounter();
                setMTimeCounter();
                display(); 
                Thread.sleep(10);
        } catch (Exception e) {
        }
           
    }
    
    public void printToList(){
        cnt2++;
        dstr += "\n" + cnt2 + ") " + lblDisp1.getText() + " " +  lblDisp2.getText() +"\n";
        txtaList.setText(dstr);
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblDisp1 = new javax.swing.JLabel();
        lblDisp2 = new javax.swing.JLabel();
        btnStart = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtaList = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblDisp1.setFont(new java.awt.Font("Tahoma", 0, 60)); // NOI18N
        lblDisp1.setText("00:00:00");

        lblDisp2.setFont(new java.awt.Font("Tahoma", 0, 40)); // NOI18N
        lblDisp2.setText("000");

        btnStart.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        btnStart.setText("Start");
        btnStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStartActionPerformed(evt);
            }
        });

        txtaList.setColumns(20);
        txtaList.setRows(5);
        jScrollPane1.setViewportView(txtaList);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(lblDisp1)
                            .addGap(18, 18, 18)
                            .addComponent(lblDisp2))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(134, 134, 134)
                            .addComponent(btnStart))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDisp1)
                    .addComponent(lblDisp2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnStart)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStartActionPerformed
            if(btnStart.getText().equals("Start")){
            btnStart.setText("Stop");
            cnt++;
            if(cnt == 1){
                t.start();
            }
            else{
                t.resume();
                
            }
        }
        else{
            btnStart.setText("Start");
            t.suspend();
            printToList();
        }

    }//GEN-LAST:event_btnStartActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StopWatch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StopWatch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StopWatch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StopWatch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new StopWatch().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnStart;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblDisp1;
    private javax.swing.JLabel lblDisp2;
    private javax.swing.JTextArea txtaList;
    // End of variables declaration//GEN-END:variables
}
